In [1]:
import numpy as np

In [2]:
ar = np.array([2, 4, 5, 3, 7, 8, 1, 9])

In [3]:
ar

array([2, 4, 5, 3, 7, 8, 1, 9])

In [7]:
ar[np.argpartition(ar, -3)[-3:]]

array([7, 8, 9])

In [14]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [15]:
np.append(a, b, axis=1)

array([[1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3]])

In [16]:
a = np.array([[1, 1, 1], [2, 2, 2]])
b = np.array([[3], [3]])

In [17]:
np.append(a, b, axis=1)

array([[1, 1, 1, 3],
       [2, 2, 2, 3]])

In [18]:
np.array([1, 0, 0], [0, 1, 0], [0, 0, 1])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
train_set = np.array([1, 2, 3])
test_set = np.array([[0, 1, 2], [1, 2, 3]])

In [21]:
resulting_set = train_set.append(test_set)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [22]:
resulting_set = np.concatenate([train_set, test_set])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [23]:
resulting_set = np.vstack([train_set, test_set])

In [24]:
resulting_set

array([[1, 2, 3],
       [0, 1, 2],
       [1, 2, 3]])